### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by SanliFaez** [SanliFaez/Commons4Academics#10]
We collaborate with experts on the theory and practice of *commons* (as in [creative commons]() or [wikimedia commons](https://commons.wikimedia.org/wiki/Main_Page)) to organize a training workshop for fellow academics to enables them organize their resources and manage them in form of a commons. We work openly because we observe the need for such training and hope to make it widely accessible.

Our cultural goal is to convince our colleagues that commons is a good formation for organization and governance of academic resources. Our ambition is to organize this project as a logical series of tasks and guidelines suitable for adaptation, revision, and reproduction for follow-up events.

## What do we need to do?

This issue is our roadmap. It's a place to start to investigate the myriad of issues that you can contribute to. 

Please check out our [contribution guidelines](../CONTRIBUTING.md) and [code of conduct](../CODE_OF_CONDUCT.md) to help you get started, and the [README](../README.md) for an overview if you haven't read it yet!

## Timeline of activities
- [x] fix workshop date and place --> Tuesday 14th May, Academy building, Utrecht 
- [x] confirmation from keynote speakers
- [x] complete the workshop description, #6 and [readme](https://github.com/SanliFaez/Commons4Academics/blob/master/README.md) (-8 weeks)
- [x] complete the workshop program, #1  (-8 weeks)
- [x] discuss program with main speakers (-7 weeks)
- [x] create the registration form, #2  (-7 weeks)
## Milestone [Workshop registration open](https://github.com/SanliFaez/Commons4Academics/milestone/2)

- [x] spread the word to potential participants #8  (-7 weeks)
- [x] choose the main cases for afternoon discussion (-6 weeks)
- [ ] work out information for main case (-5 weeks) 
- [x] create participants survey (-4 weeks)
- [ ] complete workshop program with abstracts (-4 weeks)
- [x] create workshop 1-page website #9 (-4 weeks)
- [ ] send participants survey and preparation material (-3 weeks)
- [x] confirm catering and logistics (-2 weeks)
- [x] discuss workshop documentation with reporter (-2 weeks)
## Milestone [1st C4A Workshop](https://github.com/SanliFaez/Commons4Academics/milestone/1)

- [ ] review workshop report #3  (+2 weeks)
- [ ] compile organizers cookbook #4  (+2 weeks)
- [ ] revised repository aimed at reproducing the workshop (+4 weeks)
## Milestone [1st C4A projects goes live](https://github.com/SanliFaez/Commons4Academics/milestone/3)

- [ ] create list for sister workshops
